// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiSeAjjY4X9St0v-szZnTQEukytmIzHQ8',
    appId: '1:1023386218038:android:b96149ebefbaef26e23297',
    messagingSenderId: '1023386218038',
    projectId: 'to-do-flutter-7d5cb',
    storageBucket: 'to-do-flutter-7d5cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDIVAHvze1SvLifqCgYVXwittGrM4N00g',
    appId: '1:1023386218038:ios:71b7add97bc329ede23297',
    messagingSenderId: '1023386218038',
    projectId: 'to-do-flutter-7d5cb',
    storageBucket: 'to-do-flutter-7d5cb.appspot.com',
    iosClientId: '1023386218038-4l5uu07sgs8jlef3p2o1flop4357shvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDIVAHvze1SvLifqCgYVXwittGrM4N00g',
    appId: '1:1023386218038:ios:35db8eb5643ab227e23297',
    messagingSenderId: '1023386218038',
    projectId: 'to-do-flutter-7d5cb',
    storageBucket: 'to-do-flutter-7d5cb.appspot.com',
    iosClientId: '1023386218038-58dsm3le6pchhuannvn656aggdbtvmgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoFlutter.RunnerTests',
  );
}
